# Generated by Django 5.2.1 on 2025-06-22 16:54

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_alter_teaminvitelink_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(verbose_name='Config data')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('type', models.CharField(choices=[('P', 'PlanningPoker'), ('R', 'Retrospective')], max_length=1, verbose_name='Game type')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='LobbyGameState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Stage name')),
                ('completed', models.BooleanField(default=False, verbose_name='Is completed stage')),
                ('result_data', models.JSONField(default=dict, verbose_name='Result data')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameinstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskEvaluationGameState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Stage name')),
                ('completed', models.BooleanField(default=False, verbose_name='Is completed stage')),
                ('result_data', models.JSONField(default=dict, verbose_name='Result data')),
                ('tasks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None)),
                ('current_task', models.CharField(blank=True, null=True, verbose_name='Current task')),
                ('players_votes', models.JSONField(default=dict, verbose_name='Players votes')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameinstance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
