# Generated by Django 5.2.1 on 2025-06-26 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='host_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL, verbose_name='Hoted by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='status',
            field=models.CharField(choices=[('O', 'Opened'), ('S', 'Started'), ('F', 'Finisehd'), ('C', 'Closed')], default='O', max_length=1, verbose_name='Game status'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('F', 'Facilitator'), ('P', 'Player')], default='P', max_length=1, verbose_name='Player role')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.gameinstance', verbose_name='Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'constraints': [models.UniqueConstraint(fields=('user', 'game'), name='unique_game_players', violation_error_message='Unique player in that game already exist')],
            },
        ),
    ]
