# Generated by Django 5.2.1 on 2025-06-27 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gameinstance_host_by_gameinstance_status_player'),
        ('teams', '0004_alter_teaminvitelink_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskevaluationgamestate',
            name='game',
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='teams.team'),
        ),
        migrations.DeleteModel(
            name='LobbyGameState',
        ),
        migrations.DeleteModel(
            name='TaskEvaluationGameState',
        ),
    ]
