# Generated by Django 5.2.1 on 2025-06-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_taskevaluationgamestate_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.DeleteModel(
            name='GameInstance',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
