services:
  db:
    image: postgres:17
    container_name: pokeroom-postgres-database
    restart: always
    env_file:
      - .env
    volumes:
      - ./storage/postgres-main:/var/lib/postgresql/data
    ports:
      - 5432:5432

  django:
    image: pokeroom-django-docker
    container_name: pokeroom-django-backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db

networks:
  default:
    name: pokeroom-network