# Generated by Django 5.2.1 on 2025-05-13 12:20

import datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='TeamInviteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default='ZzFTpaQ6KDbiTbu0Zxgnvg', editable=False, max_length=100, verbose_name='Token')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Token created date')),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 5, 14, 12, 20, 57, 23235, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Token expires date')),
            ],
            options={
                'verbose_name': 'Team invitelink',
                'verbose_name_plural': 'Team invitelinks',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('O', 'Owner'), ('M', 'Moderator'), ('D', 'Default')], max_length=1, verbose_name='Role')),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invited date')),
            ],
        ),
    ]
