# Generated by Django 5.2.1 on 2025-05-13 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 18, 1, 45, 244466, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Token expires date'),
        ),
        migrations.AlterField(
            model_name='teaminvitelink',
            name='token',
            field=models.CharField(default='0E6QvFNeHxIhXp7iILVFlw', editable=False, max_length=100, verbose_name='Token'),
        ),
    ]
