# Generated by Django 5.2.1 on 2025-06-26 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teaminvitelink_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 17, 29, 26, 90594, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Token expires date'),
        ),
        migrations.AlterField(
            model_name='teaminvitelink',
            name='token',
            field=models.CharField(default='ac0EN274iAjczEH4Y5ZF7g', editable=False, max_length=100, unique=True, verbose_name='Token'),
        ),
    ]
