# Generated by Django 5.2.1 on 2025-05-14 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teaminvitelink_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 12, 2, 31, 214099, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Token expires date'),
        ),
        migrations.AlterField(
            model_name='teaminvitelink',
            name='token',
            field=models.CharField(default='37p0ut5Jhe6SmY_wWM_Ing', editable=False, max_length=100, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('O', 'Owner'), ('M', 'Moderator'), ('D', 'Default')], default='D', max_length=1, verbose_name='Role'),
        ),
    ]
