# Generated by Django 5.2.1 on 2025-06-27 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teaminvitelink_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 28, 19, 33, 33, 316692, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Token expires date'),
        ),
        migrations.AlterField(
            model_name='teaminvitelink',
            name='token',
            field=models.CharField(default='C2OYjstFZ_7fxpDTq-KSPg', editable=False, max_length=100, unique=True, verbose_name='Token'),
        ),
    ]
