# Generated by Django 5.2.1 on 2025-05-14 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_teaminvitelink_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 18, 45, 22, 268336, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Token expires date'),
        ),
        migrations.AlterField(
            model_name='teaminvitelink',
            name='token',
            field=models.CharField(default='0yrKY5PJoo0JNVc7b1SVVQ', editable=False, max_length=100, verbose_name='Token'),
        ),
    ]
