# Generated by Django 5.2.1 on 2025-06-11 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_teaminvitelink_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='Membership',
        ),
        migrations.RemoveField(
            model_name='teaminvitelink',
            name='team_id',
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='unique_membership', violation_error_message='Membership with that user and team is already exist.'),
        ),
        migrations.DeleteModel(
            name='TeamInviteLink',
        ),
    ]
