# Generated by Django 5.2.1 on 2025-06-21 12:50

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_membership_unique_membership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInviteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default='sOdVD3dI9X8bBsJ1Dwvm_w', editable=False, max_length=100, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 21, 12, 50, 45, 379425), editable=False, verbose_name='Token created date')),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 6, 22, 12, 50, 45, 379443), editable=False, verbose_name='Token expires date')),
                ('team_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite_link', to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team invitelink',
                'verbose_name_plural': 'Team invitelinks',
            },
        ),
    ]
