# Generated by Django 5.2.1 on 2025-06-21 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_teaminvitelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitelink',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 12, 51, 27, 659111, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Token created date'),
        ),
        migrations.AlterField(
            model_name='teaminvitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 12, 51, 27, 659129, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Token expires date'),
        ),
        migrations.AlterField(
            model_name='teaminvitelink',
            name='token',
            field=models.CharField(default='0MQC7yqC6pozgBBA08LPGg', editable=False, max_length=100, unique=True, verbose_name='Token'),
        ),
    ]
