# Generated by Django 5.2.1 on 2025-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_pokeroomuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeroomuser',
            name='email',
            field=models.EmailField(blank=True, default=None, error_messages={'unique': 'A user with that email already exists.'}, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
