# Generated by Django 5.2.1 on 2025-06-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_pokeroomuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeroomuser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='pokeroomuser',
            name='telegram_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='telegram id'),
        ),
    ]
