# Generated by Django 5.2.1 on 2025-06-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_pokeroomuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeroomuser',
            name='telegram_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='telegram id'),
        ),
    ]
