# Generated by Django 5.2.1 on 2025-07-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_pokeroomuser_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokeroomuser',
            name='image_url',
        ),
    ]
