# Generated by Django 5.2.1 on 2025-05-14 12:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_alter_teaminvitelink_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('O', 'Opened'), ('S', 'Started'), ('F', 'Finished'), ('C', 'Closed')], max_length=1, verbose_name="Room's stats")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('target_game', models.CharField(choices=[('P', 'PokerPlanning')], max_length=1, verbose_name='Target game strategy')),
                ('video_call_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Video call link')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='teams.team', verbose_name="Team's room")),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomsMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Guest token')),
                ('role', models.CharField(choices=[('H', 'Host'), ('M', 'Member'), ('G', 'Guest')], max_length=1, verbose_name='Role')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_members', to='rooms.room', verbose_name='Room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_rooms', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
